In [62]:
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
############## DATEI LADEN ##############

# Pfad zur CSV-Datei
file_path = '../participant_package/reefer_release.csv'

# Lade die Daten in einen DataFrame
df_reefer = pd.read_csv(file_path, sep=';', decimal=',')

# Zeige die ersten paar Zeilen an
df_reefer.head(50)

,container_visit_uuid,customer_uuid,container_uuid,HardwareType,EventTime,AvPowerCons,TtlEnergyConsHour,TtlEnergyCons,TemperatureSetPoint,TemperatureAmbient,TemperatureReturn,RemperatureSupply,ContainerSize,stack_tier
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 00:00:00.000,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,-19.950000,40.0,1.0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 01:00:00.000,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,-19.900000,40.0,1.0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 02:00:00.000,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,-19.850000,40.0,1.0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 03:00:00.000,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,-19.800000,40.0,1.0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 04:00:00.000,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,-19.766667,40.0,1.0
5,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 05:00:00.000,948.925318,948.117326,1.524053e+06,-18.0,11.275000,-17.800000,-19.725000,40.0,1.0
6,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 06:00:00.000,943.195856,942.197902,1.524995e+06,-18.0,11.266667,-17.800000,-19.666667,40.0,1.0
7,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 07:00:00.000,461.699028,461.312800,1.525456e+06,-18.0,10.200000,-13.000000,-18.500000,40.0,1.0
8,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 08:00:00.000,919.601632,919.536424,1.526376e+06,-18.0,11.533333,-17.566667,-18.933333,40.0,1.0
9,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 09:00:00.000,916.454445,915.682541,1.527291e+06,-18.0,11.200000,-17.600000,-19.650000,40.0,1.0
10,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 10:00:00.000,907.793881,907.974506,1.528199e+06,-18.0,11.100000,-17.900000,-19.950000,40.0,1.0
11,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 11:00:00.000,887.743038,887.333508,1.529087e+06,-18.0,11.266667,-18.000000,-20.066667,40.0,1.0
12,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 12:00:00.000,913.504323,913.308033,1.530000e+06,-18.0,11.350000,-18.000000,-20.050000,40.0,1.0
13,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 13:00:00.000,928.013366,928.186031,1.530928e+06,-18.0,11.000000,-18.000000,-20.100000,40.0,1.0
14,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 14:00:00.000,970.747584,970.725140,1.531899e+06,-18.0,11.400000,-18.075000,-20.100000,40.0,1.0
15,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 15:00:00.000,908.022028,908.056494,1.532807e+06,-18.0,11.200000,-18.100000,-20.100000,40.0,1.0
16,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 16:00:00.000,921.501136,921.306738,1.533728e+06,-18.0,11.425000,-18.100000,-20.100000,40.0,1.0
17,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 17:00:00.000,934.422131,933.950085,1.534662e+06,-18.0,11.566667,-18.100000,-20.166667,40.0,1.0
18,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 18:00:00.000,949.014749,948.620771,1.535611e+06,-18.0,10.650000,-18.100000,-20.200000,40.0,1.0
19,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 19:00:00.000,941.528349,941.694472,1.536552e+06,-18.0,10.425000,-18.175000,-20.200000,40.0,1.0
20,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 20:00:00.000,916.994942,915.835980,1.537468e+06,-18.0,9.900000,-18.166667,-20.133333,40.0,1.0
21,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 21:00:00.000,928.151947,931.418264,1.538400e+06,-18.0,9.850000,-18.100000,-20.000000,40.0,1.0
22,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 22:00:00.000,902.347303,902.330499,1.539302e+06,-18.0,9.775000,-18.100000,-20.000000,40.0,1.0
23,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 23:00:00.000,875.333560,875.318754,1.540177e+06,-18.0,9.766667,-18.100000,-20.000000,40.0,1.0
24,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 00:00:00.000,878.198807,878.359382,1.541056e+06,-18.0,10.150000,-18.100000,-20.000000,40.0,1.0
25,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 01:00:00.000,900.104831,900.259960,1.541956e+06,-18.0,9.300000,-18.100000,-20.000000,40.0,1.0
26,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 02:00:00.000,927.552590,927.347699,1.542883e+06,-18.0,8.233333,-18.200000,-20.066667,40.0,1.0
27,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 03:00:00.000,916.380133,916.841510,1.543800e+06,-18.0,8.175000,-18.200000,-19.875000,40.0,1.0
28,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 04:00:00.000,898.343263,898.251075,1.544698e+06,-18.0,7.933333,-18.200000,-19.900000,40.0,1.0
29,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 05:00:00.000,924.202125,924.267386,1.545623e+06,-18.0,8.275000,-18.200000,-19.900000,40.0,1.0
30,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 06:00:00.000,929.404211,928.433889,1.546551e+06,-18.0,8.200000,-18.150000,-19.800000,40.0,1.0
31,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 07:00:00.000,908.541644,908.730410,1.547460e+06,-18.0,7.500000,-18.000000,-19.733333,40.0,1.0
32,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 08:00:00.000,899.906028,900.084369,1.548360e+06,-18.0,8.075000,-18.000000,-19.800000,40.0,1.0
33,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 09:00:00.000,919.204075,921.360961,1.549281e+06,-18.0,8.600000,-18.025000,-19.775000,40.0,1.0
34,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 10:00:00.000,923.332455,922.431046,1.550204e+06,-18.0,8.700000,-18.000000,-19.766667,40.0,1.0
35,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 11:00:00.000,908.494774,912.873206,1.551117e+06,-18.0,9.350000,-18.000000,-19.725000,40.0,1.0
36,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 12:00:00.000,899.997511,899.390442,1.552016e+06,-18.0,8.966667,-17.966667,-19.666667,40.0,1.0
37,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 13:00:00.000,908.089347,908.048742,1.552924e+06,-18.0,9.025000,-17.900000,-19.675000,40.0,1.0
38,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 14:00:00.000,909.873606,911.790968,1.553836e+06,-18.0,9.050000,-17.900000,-19.650000,40.0,1.0
39,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 15:00:00.000,881.266477,881.275321,1.554717e+06,-18.0,8.500000,-17.900000,-19.633333,40.0,1.0
40,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 16:00:00.000,921.650531,920.446736,1.555638e+06,-18.0,8.350000,-17.925000,-19.675000,40.0,1.0
41,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 17:00:00.000,949.849143,950.039557,1.556588e+06,-18.0,7.466667,-18.000000,-19.700000,40.0,1.0
42,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 18:00:00.000,936.463493,936.589914,1.557524e+06,-18.0,7.425000,-18.075000,-19.700000,40.0,1.0
43,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 19:00:00.000,927.383561,926.779445,1.558451e+06,-18.0,7.575000,-18.100000,-19.800000,40.0,1.0
44,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 20:00:00.000,903.230570,903.625456,1.559355e+06,-18.0,7.325000,-18.100000,-19.775000,40.0,1.0
45,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 21:00:00.000,947.727928,946.796583,1.560301e+06,-18.0,7.366667,-18.100000,-19.766667,40.0,1.0
46,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 22:00:00.000,901.975615,901.469564,1.561203e+06,-18.0,7.575000,-18.125000,-19.750000,40.0,1.0
47,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-02 23:00:00.000,891.134808,889.606209,1.562092e+06,-18.0,7.566667,-18.133333,-19.800000,40.0,1.0
48,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-03 00:00:00.000,875.846789,875.410732,1.562968e+06,-18.0,7.200000,-18.000000,-19.800000,40.0,1.0
49,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-03 01:00:00.000,885.338550,885.542368,1.563853e+06,-18.0,6.850000,-18.000000,-19.800000,40.0,1.0

In [64]:
############## Spaltennamen von Leerzeichen befreien ##############

# 1. Leerzeichen am Anfang/Ende entfernen und Leerzeichen durch Unterstriche ersetzen
df_reefer.columns = df_reefer.columns.str.strip().str.replace(' ', '_')

# 2. Alles kleinschreiben (optional, aber extrem hilfreich für schnelles Tippen)
df_reefer.columns = df_reefer.columns.str.lower()

# Kurzer Check der neuen Namen
print("Bereinigte Spaltennamen in df_reefer:")
print(df_reefer.columns.tolist())

Bereinigte Spaltennamen in df_reefer:
['container_visit_uuid', 'customer_uuid', 'container_uuid', 'hardwaretype', 'eventtime', 'avpowercons', 'ttlenergyconshour', 'ttlenergycons', 'temperaturesetpoint', 'temperatureambient', 'temperaturereturn', 'remperaturesupply', 'containersize', 'stack_tier']

In [65]:
# 1. Grundstruktur und Datentypen
print("--- Info ---")
print(df_reefer.info())

--- Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3774557 entries, 0 to 3774556
Data columns (total 14 columns):
 #   Column                Dtype
---  ------                -----
 0   container_visit_uuid  object
 1   customer_uuid         object
 2   container_uuid        object
 3   hardwaretype          object
 4   eventtime             object
 5   avpowercons           float64
 6   ttlenergyconshour     float64
 7   ttlenergycons         float64
 8   temperaturesetpoint   float64
 9   temperatureambient    float64
 10  temperaturereturn     float64
 11  remperaturesupply     float64
 12  containersize         float64
 13  stack_tier            float64
dtypes: float64(9), object(5)
memory usage: 403.2+ MB
None

In [66]:
# 2. Wie viele Missings pro Spalte?
print("\n--- Fehlende Werte ---")
missings = df_reefer.isna().sum()
print(missings[missings > 0]) # Zeigt nur Spalten mit Fehlern

--- Fehlende Werte ---
customer_uuid       11
containersize     1994
stack_tier       12471
dtype: int64

In [67]:
############## Zeilen löschen, bei denen 'containersize' fehlt ##############


df_reefer = df_reefer.dropna(subset=['containersize'])

# 2. Missings in 'stack_tier' durch den Wert 1 ersetzen
df_reefer['stack_tier'] = df_reefer['stack_tier'].fillna(1)

# Kurze Erfolgskontrolle
print(f"✅ Zeilen mit fehlender Größe gelöscht. Neue Zeilenanzahl: {len(df_reefer)}")
print(f"✅ Verbleibende Missings in 'stack_tier': {df_reefer['stack_tier'].isna().sum()}")

# Optional: Prüfen, ob stack_tier jetzt den richtigen Datentyp hat (z.B. Integer)
# df_reefer['stack_tier'] = df_reefer['stack_tier'].astype(int)

✅ Zeilen mit fehlender Größe gelöscht. Neue Zeilenanzahl: 3772563
✅ Verbleibende Missings in 'stack_tier': 0

In [68]:
# Berechnung der Missings
missing_count = df_reefer.isna().sum()
missing_percentage = (missing_count / len(df_reefer)) * 100

# Zusammenführen in eine schöne Tabelle
missing_report = pd.DataFrame({
    'Anzahl Missings': missing_count,
    'Anteil (%)': missing_percentage.round(2)
})

# Nur Spalten anzeigen, die tatsächlich Missings haben, sortiert nach Wichtigkeit
missing_report = missing_report[missing_report['Anzahl Missings'] > 0].sort_values(by='Anteil (%)', ascending=False)

print(f"Gesamtanzahl Zeilen im Datensatz: {len(df_reefer)}")
print("-" * 40)
if missing_report.empty:
    print("✅ Wahnsinn! Der Datensatz ist jetzt komplett sauber (keine Missings).")
else:
    print(missing_report)

Gesamtanzahl Zeilen im Datensatz: 3772563
----------------------------------------
✅ Wahnsinn! Der Datensatz ist jetzt komplett sauber (keine Missings).

In [69]:
df_reefer

,container_visit_uuid,customer_uuid,container_uuid,hardwaretype,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,remperaturesupply,containersize,stack_tier
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 00:00:00.000,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,-19.950000,40.0,1.0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 01:00:00.000,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,-19.900000,40.0,1.0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 02:00:00.000,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,-19.850000,40.0,1.0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 03:00:00.000,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,-19.800000,40.0,1.0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 04:00:00.000,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,-19.766667,40.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3774552,87ee96e3-a5c9-f214-3c76-12bf9c2bea53,8e8e76cd-ec84-0745-b968-38459ecacc17,7ceac6d7-5c28-a993-804e-16669c5f56b7,SCC6,2026-01-10 06:00:00.000,1039.230485,1021.923559,1.513898e+03,13.3,-1.550000,13.475000,13.450000,40.0,3.0
3774553,b5619984-d78d-2206-64ba-d322ef54df28,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,b906b83d-834a-563a-5791-22f408d0fd5f,SCC6,2026-01-10 06:00:00.000,938.529856,670.968746,6.709687e+02,13.3,-2.800000,13.000000,12.866667,40.0,3.0
3774554,7d41f7db-eac1-2054-8d57-24e2820a2e5a,13dbe4f4-735d-726f-a8b8-61578d90517c,8d5e4c57-cb15-0793-dba7-af88cb69da76,ML3,2026-01-10 06:00:00.000,706.216293,10.979653,1.097965e+01,-20.0,-3.200000,-11.400000,-12.400000,40.0,1.0
3774555,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,SCC6,2026-01-10 05:00:00.000,969.948452,80.153180,8.015318e+01,13.3,-2.400000,12.700000,11.800000,40.0,1.0
3774556,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,SCC6,2026-01-10 06:00:00.000,866.025404,866.017161,9.461703e+02,13.3,-2.400000,13.400000,13.466667,40.0,1.0

In [70]:
# remove super long stay outliers
uuids_to_remove = ["e81b2358-de43-a16e-099e-4561b75d88ee", "fb8c5f5c-b434-02b4-40d7-eb521a254192"]  # UUIDs to remove
df = df_reefer[~df_reefer['container_visit_uuid'].isin(uuids_to_remove)]

print(f"Rows removed: {len(df)} rows remaining")

Rows removed: 3763789 rows remaining

In [71]:
df_reefer['stay_total_hours_elapsed'] = df_reefer.groupby('container_visit_uuid').cumcount() + 1
df_reefer

,container_visit_uuid,customer_uuid,container_uuid,hardwaretype,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,remperaturesupply,containersize,stack_tier,stay_total_hours_elapsed
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 00:00:00.000,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,-19.950000,40.0,1.0,1
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 01:00:00.000,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,-19.900000,40.0,1.0,2
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 02:00:00.000,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,-19.850000,40.0,1.0,3
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 03:00:00.000,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,-19.800000,40.0,1.0,4
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,DecosVa,2025-01-01 04:00:00.000,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,-19.766667,40.0,1.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3774552,87ee96e3-a5c9-f214-3c76-12bf9c2bea53,8e8e76cd-ec84-0745-b968-38459ecacc17,7ceac6d7-5c28-a993-804e-16669c5f56b7,SCC6,2026-01-10 06:00:00.000,1039.230485,1021.923559,1.513898e+03,13.3,-1.550000,13.475000,13.450000,40.0,3.0,2
3774553,b5619984-d78d-2206-64ba-d322ef54df28,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,b906b83d-834a-563a-5791-22f408d0fd5f,SCC6,2026-01-10 06:00:00.000,938.529856,670.968746,6.709687e+02,13.3,-2.800000,13.000000,12.866667,40.0,3.0,1
3774554,7d41f7db-eac1-2054-8d57-24e2820a2e5a,13dbe4f4-735d-726f-a8b8-61578d90517c,8d5e4c57-cb15-0793-dba7-af88cb69da76,ML3,2026-01-10 06:00:00.000,706.216293,10.979653,1.097965e+01,-20.0,-3.200000,-11.400000,-12.400000,40.0,1.0,1
3774555,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,SCC6,2026-01-10 05:00:00.000,969.948452,80.153180,8.015318e+01,13.3,-2.400000,12.700000,11.800000,40.0,1.0,1
3774556,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,SCC6,2026-01-10 06:00:00.000,866.025404,866.017161,9.461703e+02,13.3,-2.400000,13.400000,13.466667,40.0,1.0,2

In [72]:
# Liste der zu löschenden Spalten
#cols_to_drop = ['customer_uuid', 'container_uuid', 'container_visit_uuid']

# Spalten droppen
#df_reefer = df_reefer.drop(columns=cols_to_drop, errors='ignore')

# Falls die Spalte bei dir 'container_visit_uid' (mit i statt u) hieß:
#df_reefer = df_reefer.drop(columns=['container_visit_uid'], errors='ignore')

#print("✅ Die ID-Spalten wurden erfolgreich entfernt.")
#print(f"Verbleibende Spalten im df_reefer: {df_reefer.columns.tolist()}")

In [73]:
############## Hersteller Hotencoding ##############

# One-Hot-Encoding für die Spalte 'hardwaretype'
# dtype=int sorgt dafür, dass 0 und 1 statt True/False verwendet werden
df_reefer = pd.get_dummies(df_reefer, columns=['hardwaretype'], dtype=int)

# Kurze Kontrolle der neuen Spalten
print(df_reefer.columns)
df_reefer.head()

Index(['container_visit_uuid', 'customer_uuid', 'container_uuid', 'eventtime',
       'avpowercons', 'ttlenergyconshour', 'ttlenergycons',
       'temperaturesetpoint', 'temperatureambient', 'temperaturereturn',
       'remperaturesupply', 'containersize', 'stack_tier',
       'stay_total_hours_elapsed', 'hardwaretype_DecosIIIc',
       'hardwaretype_DecosIIId', 'hardwaretype_DecosIIId1',
       'hardwaretype_DecosIIIe', 'hardwaretype_DecosIIIf',
       'hardwaretype_DecosIIIg', 'hardwaretype_DecosIIIh',
       'hardwaretype_DecosIIIj', 'hardwaretype_DecosVa',
       'hardwaretype_DecosVb', 'hardwaretype_ML2i', 'hardwaretype_ML3',
       'hardwaretype_ML5', 'hardwaretype_MP3000A', 'hardwaretype_MP4000',
       'hardwaretype_MPC2000', 'hardwaretype_MPC2000ID', 'hardwaretype_RCCU5',
       'hardwaretype_SCC6'],
      dtype='object')

,container_visit_uuid,customer_uuid,container_uuid,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,...,hardwaretype_DecosVb,hardwaretype_ML2i,hardwaretype_ML3,hardwaretype_ML5,hardwaretype_MP3000A,hardwaretype_MP4000,hardwaretype_MPC2000,hardwaretype_MPC2000ID,hardwaretype_RCCU5,hardwaretype_SCC6
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 00:00:00.000,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,...,0,0,0,0,0,0,0,0,0,0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 01:00:00.000,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,...,0,0,0,0,0,0,0,0,0,0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 02:00:00.000,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,...,0,0,0,0,0,0,0,0,0,0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 03:00:00.000,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,...,0,0,0,0,0,0,0,0,0,0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 04:00:00.000,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,...,0,0,0,0,0,0,0,0,0,0

In [74]:
# Sicherstellen, dass eventtime als Datetime vorliegt
df_reefer['eventtime'] = pd.to_datetime(df_reefer['eventtime'])

# Auf volle Stunde runden, damit wirklich stündlich gruppiert wird
df_reefer['hour_timestamp'] = df_reefer['eventtime'].dt.floor('h')

# Datum für die Tagesbetrachtung ableiten
df_reefer['date'] = df_reefer['hour_timestamp'].dt.date

# 1) Über alle Container hinweg den Gesamtverbrauch pro Stunde berechnen
hourly_energy = (
    df_reefer
    .groupby(['date', 'hour_timestamp'], as_index=False)['ttlenergyconshour']
    .sum()
    .rename(columns={'ttlenergyconshour': 'total_energy_hour'})
)

# 2) Pro Tag den höchsten stündlichen Gesamtverbrauch bestimmen
hourly_energy['daily_max_energy'] = (
    hourly_energy
    .groupby('date')['total_energy_hour']
    .transform('max')
)

# 3) Neue Kennzeichnung:
#    1 = diese Stunde ist die Peak-Stunde des Tages
#    0 = diese Stunde ist nicht die Peak-Stunde des Tages
hourly_energy['is_energy_peak_hour'] = (
    hourly_energy['total_energy_hour'] == hourly_energy['daily_max_energy']
).astype(int)

# 4) Die Peak-Kennzeichnung zurück an den ursprünglichen DataFrame anhängen
df_reefer = df_reefer.merge(
    hourly_energy[['hour_timestamp', 'is_energy_peak_hour']],
    on='hour_timestamp',
    how='left'
)

# 5) Hilfsspalten wieder entfernen, falls du sie nicht behalten möchtest
df_reefer.drop(columns=['hour_timestamp', 'date'], inplace=True)

# Kurze Kontrolle
print(df_reefer[['eventtime', 'ttlenergyconshour', 'is_energy_peak_hour']].head())
df_reefer.head()

            eventtime  ttlenergyconshour  is_energy_peak_hour
0 2025-01-01 00:00:00         887.437326                    0
1 2025-01-01 01:00:00         928.094827                    0
2 2025-01-01 02:00:00         929.299938                    0
3 2025-01-01 03:00:00         925.736719                    0
4 2025-01-01 04:00:00         944.842351                    0

,container_visit_uuid,customer_uuid,container_uuid,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,...,hardwaretype_ML2i,hardwaretype_ML3,hardwaretype_ML5,hardwaretype_MP3000A,hardwaretype_MP4000,hardwaretype_MPC2000,hardwaretype_MPC2000ID,hardwaretype_RCCU5,hardwaretype_SCC6,is_energy_peak_hour
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 00:00:00,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,...,0,0,0,0,0,0,0,0,0,0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 01:00:00,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,...,0,0,0,0,0,0,0,0,0,0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 02:00:00,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,...,0,0,0,0,0,0,0,0,0,0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 03:00:00,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,...,0,0,0,0,0,0,0,0,0,0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 04:00:00,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,...,0,0,0,0,0,0,0,0,0,0

In [75]:
df_reefer

,container_visit_uuid,customer_uuid,container_uuid,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,...,hardwaretype_ML2i,hardwaretype_ML3,hardwaretype_ML5,hardwaretype_MP3000A,hardwaretype_MP4000,hardwaretype_MPC2000,hardwaretype_MPC2000ID,hardwaretype_RCCU5,hardwaretype_SCC6,is_energy_peak_hour
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 00:00:00,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,...,0,0,0,0,0,0,0,0,0,0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 01:00:00,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,...,0,0,0,0,0,0,0,0,0,0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 02:00:00,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,...,0,0,0,0,0,0,0,0,0,0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 03:00:00,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,...,0,0,0,0,0,0,0,0,0,0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 04:00:00,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772558,87ee96e3-a5c9-f214-3c76-12bf9c2bea53,8e8e76cd-ec84-0745-b968-38459ecacc17,7ceac6d7-5c28-a993-804e-16669c5f56b7,2026-01-10 06:00:00,1039.230485,1021.923559,1.513898e+03,13.3,-1.550000,13.475000,...,0,0,0,0,0,0,0,0,1,0
3772559,b5619984-d78d-2206-64ba-d322ef54df28,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,b906b83d-834a-563a-5791-22f408d0fd5f,2026-01-10 06:00:00,938.529856,670.968746,6.709687e+02,13.3,-2.800000,13.000000,...,0,0,0,0,0,0,0,0,1,0
3772560,7d41f7db-eac1-2054-8d57-24e2820a2e5a,13dbe4f4-735d-726f-a8b8-61578d90517c,8d5e4c57-cb15-0793-dba7-af88cb69da76,2026-01-10 06:00:00,706.216293,10.979653,1.097965e+01,-20.0,-3.200000,-11.400000,...,0,1,0,0,0,0,0,0,0,0
3772561,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,2026-01-10 05:00:00,969.948452,80.153180,8.015318e+01,13.3,-2.400000,12.700000,...,0,0,0,0,0,0,0,0,1,0
3772562,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,2026-01-10 06:00:00,866.025404,866.017161,9.461703e+02,13.3,-2.400000,13.400000,...,0,0,0,0,0,0,0,0,1,0

KEINE MISSINGS MEHR !!!!!!!!!!!!!!!!!!!!!!!!!!

AB JZ WETTER!!!!!!!!!!!!!!!!!!!!!!

In [76]:
%pip install openmeteo-requests
%pip install requests-cache retry-requests numpy pandas

Requirement already satisfied: openmeteo-requests in c:\users\asmus\anaconda3\lib\site-packages (1.7.5)
Requirement already satisfied: niquests>=3.15.2 in c:\users\asmus\anaconda3\lib\site-packages (from openmeteo-requests) (3.18.4)
Requirement already satisfied: openmeteo-sdk>=1.22.0 in c:\users\asmus\anaconda3\lib\site-packages (from openmeteo-requests) (1.26.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asmus\anaconda3\lib\site-packages (from niquests>=3.15.2->openmeteo-requests) (3.4.4)
Requirement already satisfied: urllib3-future<3,>=2.13.903 in c:\users\asmus\anaconda3\lib\site-packages (from niquests>=3.15.2->openmeteo-requests) (2.19.904)
Requirement already satisfied: wassima<3,>=1.0.1 in c:\users\asmus\anaconda3\lib\site-packages (from niquests>=3.15.2->openmeteo-requests) (2.0.6)
Requirement already satisfied: h11<1.0.0,>=0.11.0 in c:\users\asmus\anaconda3\lib\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (0.16.0)
Requirement already satisfied: jh2<6.0.0,>=5.0.3 in c:\users\asmus\anaconda3\lib\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (5.0.11)
Requirement already satisfied: qh3<2.0.0,>=1.5.4 in c:\users\asmus\anaconda3\lib\site-packages (from urllib3-future<3,>=2.13.903->niquests>=3.15.2->openmeteo-requests) (1.7.1)
Requirement already satisfied: flatbuffers==25.9.23 in c:\users\asmus\anaconda3\lib\site-packages (from openmeteo-sdk>=1.22.0->openmeteo-requests) (25.9.23)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: requests-cache in c:\users\asmus\anaconda3\lib\site-packages (1.3.1)
Requirement already satisfied: retry-requests in c:\users\asmus\anaconda3\lib\site-packages (2.0.0)
Requirement already satisfied: numpy in c:\users\asmus\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: pandas in c:\users\asmus\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: attrs>=21.2 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (4.5.0)
Requirement already satisfied: requests>=2.22 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (2.32.5)
Requirement already satisfied: url-normalize>=2.0 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (2.2.1)
Requirement already satisfied: urllib3>=1.25.5 in c:\users\asmus\anaconda3\lib\site-packages (from requests-cache) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asmus\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asmus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asmus\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\asmus\anaconda3\lib\site-packages (from cattrs>=22.2->requests-cache) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\asmus\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\asmus\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asmus\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asmus\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

In [77]:
import openmeteo_requests

import pandas as pd
import requests_cache
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://historical-forecast-api.open-meteo.com/v1/forecast"
params = {
	"latitude": 53.5507,
	"longitude": 9.993,
	"start_date": "2025-01-01",
	"end_date": "2026-03-31",
	"hourly": ["temperature_2m", "precipitation", "wind_speed_10m", "wind_direction_10m", "cloud_cover"],
	"timezone": "Europe/Berlin",
}
responses = openmeteo.weather_api(url, params = params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates: {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation: {response.Elevation()} m asl")
print(f"Timezone: {response.Timezone()}{response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0: {response.UtcOffsetSeconds()}s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(1).ValuesAsNumpy()
hourly_wind_speed_10m = hourly.Variables(2).ValuesAsNumpy()
hourly_wind_direction_10m = hourly.Variables(3).ValuesAsNumpy()
hourly_cloud_cover = hourly.Variables(4).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time() + response.UtcOffsetSeconds(), unit = "s", utc = True),
	end =  pd.to_datetime(hourly.TimeEnd() + response.UtcOffsetSeconds(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}

hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["precipitation"] = hourly_precipitation
hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
hourly_data["wind_direction_10m"] = hourly_wind_direction_10m
hourly_data["cloud_cover"] = hourly_cloud_cover

hourly_dataframe = pd.DataFrame(data = hourly_data)
hourly_dataframe

Coordinates: 53.560001373291016°N 10.0°E
Elevation: 11.0 m asl
Timezone: b'Europe/Berlin'b'GMT+2'
Timezone difference to GMT+0: 7200s

,date,temperature_2m,precipitation,wind_speed_10m,wind_direction_10m,cloud_cover
0,2025-01-01 00:00:00+00:00,4.321500,0.0,21.599998,216.869980,100.0
1,2025-01-01 01:00:00+00:00,4.471500,0.0,24.724951,227.950851,100.0
2,2025-01-01 02:00:00+00:00,5.071500,0.0,24.967497,227.337341,100.0
3,2025-01-01 03:00:00+00:00,5.371500,0.0,22.406927,226.301880,100.0
4,2025-01-01 04:00:00+00:00,5.671500,0.0,24.798225,230.300964,100.0
...,...,...,...,...,...,...
10915,2026-03-31 19:00:00+00:00,8.471499,0.0,17.826363,316.636536,49.0
10916,2026-03-31 20:00:00+00:00,7.871500,0.0,14.618837,307.998779,60.0
10917,2026-03-31 21:00:00+00:00,7.321500,0.0,11.720751,317.489594,47.0
10918,2026-03-31 22:00:00+00:00,6.521500,0.0,11.200571,315.000092,19.0
10919,2026-03-31 23:00:00+00:00,6.171500,0.0,9.387651,302.471161,10.0

DIE FORECASTS EINEN TAG NACH VORNE SCHIEBEN!!!!

In [78]:
# 1. Identifiziere alle Spalten außer 'date'
# (Ich gehe davon aus, dass 'date' deine Anker-Spalte ist)
cols_to_shift = [col for col in hourly_dataframe.columns if col != 'date']

# 2. Verschiebe die Werte dieser Spalten um 1 Zeile nach oben
hourly_dataframe[cols_to_shift] = hourly_dataframe[cols_to_shift].shift(-24)

# 3. Die letzte Zeile entfernen, da sie nun "leer" (NaN) für die Daten-Spalten ist
hourly_dataframe = hourly_dataframe.iloc[:-24].reset_index(drop=True)

hourly_dataframe.head()

,date,temperature_2m,precipitation,wind_speed_10m,wind_direction_10m,cloud_cover
0,2025-01-01 00:00:00+00:00,5.4715,0.7,20.771093,244.323227,99.0
1,2025-01-01 01:00:00+00:00,5.3715,0.2,21.611996,240.018448,100.0
2,2025-01-01 02:00:00+00:00,5.4715,0.0,21.252199,243.869049,100.0
3,2025-01-01 03:00:00+00:00,5.5215,0.0,19.008547,245.376450,100.0
4,2025-01-01 04:00:00+00:00,4.1715,2.0,16.992609,323.615540,100.0

In [79]:
# 1. Datetime-Format erzwingen UND Zeitzonen-Info entfernen (.dt.tz_localize(None))
df_reefer['eventtime'] = pd.to_datetime(df_reefer['eventtime']).dt.tz_localize(None)
hourly_dataframe['date'] = pd.to_datetime(hourly_dataframe['date']).dt.tz_localize(None)

# 2. Der Merge (jetzt ohne Fehler)
df_reefer_combined = pd.merge(
    df_reefer, 
    hourly_dataframe, 
    left_on='eventtime', 
    right_on='date', 
    how='left'
)

# 3. Aufräumen
df_reefer_combined = df_reefer_combined.drop(columns=['date'], errors='ignore')

print(f"✅ Erfolg! Datensatz kombiniert. Spalten: {df_reefer_combined.columns.tolist()}")

✅ Erfolg! Datensatz kombiniert. Spalten: ['container_visit_uuid', 'customer_uuid', 'container_uuid', 'eventtime', 'avpowercons', 'ttlenergyconshour', 'ttlenergycons', 'temperaturesetpoint', 'temperatureambient', 'temperaturereturn', 'remperaturesupply', 'containersize', 'stack_tier', 'stay_total_hours_elapsed', 'hardwaretype_DecosIIIc', 'hardwaretype_DecosIIId', 'hardwaretype_DecosIIId1', 'hardwaretype_DecosIIIe', 'hardwaretype_DecosIIIf', 'hardwaretype_DecosIIIg', 'hardwaretype_DecosIIIh', 'hardwaretype_DecosIIIj', 'hardwaretype_DecosVa', 'hardwaretype_DecosVb', 'hardwaretype_ML2i', 'hardwaretype_ML3', 'hardwaretype_ML5', 'hardwaretype_MP3000A', 'hardwaretype_MP4000', 'hardwaretype_MPC2000', 'hardwaretype_MPC2000ID', 'hardwaretype_RCCU5', 'hardwaretype_SCC6', 'is_energy_peak_hour', 'temperature_2m', 'precipitation', 'wind_speed_10m', 'wind_direction_10m', 'cloud_cover']

In [80]:
df_reefer_combined

,container_visit_uuid,customer_uuid,container_uuid,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,...,hardwaretype_MPC2000,hardwaretype_MPC2000ID,hardwaretype_RCCU5,hardwaretype_SCC6,is_energy_peak_hour,temperature_2m,precipitation,wind_speed_10m,wind_direction_10m,cloud_cover
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 00:00:00,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,...,0,0,0,0,0,5.471500,0.7,20.771093,244.323227,99.0
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 01:00:00,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,...,0,0,0,0,0,5.371500,0.2,21.611996,240.018448,100.0
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 02:00:00,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,...,0,0,0,0,0,5.471500,0.0,21.252199,243.869049,100.0
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 03:00:00,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,...,0,0,0,0,0,5.521500,0.0,19.008547,245.376450,100.0
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 04:00:00,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,...,0,0,0,0,0,4.171500,2.0,16.992609,323.615540,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772558,87ee96e3-a5c9-f214-3c76-12bf9c2bea53,8e8e76cd-ec84-0745-b968-38459ecacc17,7ceac6d7-5c28-a993-804e-16669c5f56b7,2026-01-10 06:00:00,1039.230485,1021.923559,1.513898e+03,13.3,-1.550000,13.475000,...,0,0,0,1,0,-10.128500,0.0,4.582052,315.000092,100.0
3772559,b5619984-d78d-2206-64ba-d322ef54df28,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,b906b83d-834a-563a-5791-22f408d0fd5f,2026-01-10 06:00:00,938.529856,670.968746,6.709687e+02,13.3,-2.800000,13.000000,...,0,0,0,1,0,-10.128500,0.0,4.582052,315.000092,100.0
3772560,7d41f7db-eac1-2054-8d57-24e2820a2e5a,13dbe4f4-735d-726f-a8b8-61578d90517c,8d5e4c57-cb15-0793-dba7-af88cb69da76,2026-01-10 06:00:00,706.216293,10.979653,1.097965e+01,-20.0,-3.200000,-11.400000,...,0,0,0,0,0,-10.128500,0.0,4.582052,315.000092,100.0
3772561,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,2026-01-10 05:00:00,969.948452,80.153180,8.015318e+01,13.3,-2.400000,12.700000,...,0,0,0,1,0,-9.528501,0.0,3.826853,311.185822,60.0
3772562,6117ced6-2a54-583d-2117-7cef911d8371,d3e37c68-6378-d90b-7d07-8f1c06fbfef5,247e733a-f849-301d-58f4-7c528032e853,2026-01-10 06:00:00,866.025404,866.017161,9.461703e+02,13.3,-2.400000,13.400000,...,0,0,0,1,0,-10.128500,0.0,4.582052,315.000092,100.0

In [81]:
stack_means = (
    df_reefer_combined
    .groupby(["eventtime", "stack_tier"])["temperaturesetpoint"]
    .mean()
    .unstack()
)

# Falls die Spalten 1,2,3 nicht alle vorhanden sind, trotzdem anlegen
for col in [1, 2, 3]:
    if col not in stack_means.columns:
        stack_means[col] = np.nan

stack_means = stack_means[[1, 2, 3]]

# 2) Surrounding average je stack berechnen
stack_means["avg_surrounding_settemperature_stack_1"] = stack_means[[1, 2]].mean(axis=1)
stack_means["avg_surrounding_settemperature_stack_2"] = stack_means[[1, 2, 3]].mean(axis=1)
stack_means["avg_surrounding_settemperature_stack_3"] = stack_means[[2, 3]].mean(axis=1)

# 3) Nur die benötigten Spalten zurück in langes Format
surrounding_lookup = (
    stack_means[
        [
            "avg_surrounding_settemperature_stack_1",
            "avg_surrounding_settemperature_stack_2",
            "avg_surrounding_settemperature_stack_3",
        ]
    ]
    .reset_index()
)

# 4) Je nach stack_tier die richtige Spalte auswählen
df_reefer_combined = df_reefer_combined.merge(
    surrounding_lookup,
    on="eventtime",
    how="left"
)

df_reefer_combined["avg_sorounding_settemperature"] = np.select(
    [
        df_reefer_combined["stack_tier"] == 1,
        df_reefer_combined["stack_tier"] == 2,
        df_reefer_combined["stack_tier"] == 3,
    ],
    [
        df_reefer_combined["avg_surrounding_settemperature_stack_1"],
        df_reefer_combined["avg_surrounding_settemperature_stack_2"],
        df_reefer_combined["avg_surrounding_settemperature_stack_3"],
    ],
    default=np.nan
)

# Optional: Hilfsspalten wieder entfernen
df_reefer_combined.drop(
    columns=[
        "avg_surrounding_settemperature_stack_1",
        "avg_surrounding_settemperature_stack_2",
        "avg_surrounding_settemperature_stack_3",
    ],
    inplace=True
)

df_reefer_combined.head(50)

,container_visit_uuid,customer_uuid,container_uuid,eventtime,avpowercons,ttlenergyconshour,ttlenergycons,temperaturesetpoint,temperatureambient,temperaturereturn,...,hardwaretype_MPC2000ID,hardwaretype_RCCU5,hardwaretype_SCC6,is_energy_peak_hour,temperature_2m,precipitation,wind_speed_10m,wind_direction_10m,cloud_cover,avg_sorounding_settemperature
0,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 00:00:00,887.793488,887.437326,1.519376e+06,-18.0,9.625000,-18.100000,...,0,0,0,0,5.4715,0.7,20.771093,244.323227,99.0,NaN
1,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 01:00:00,928.909479,928.094827,1.520305e+06,-18.0,10.066667,-18.000000,...,0,0,0,0,5.3715,0.2,21.611996,240.018448,100.0,NaN
2,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 02:00:00,929.646456,929.299938,1.521234e+06,-18.0,10.250000,-17.975000,...,0,0,0,0,5.4715,0.0,21.252199,243.869049,100.0,NaN
3,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 03:00:00,923.307627,925.736719,1.522160e+06,-18.0,10.550000,-17.900000,...,0,0,0,0,5.5215,0.0,19.008547,245.376450,100.0,NaN
4,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 04:00:00,945.029192,944.842351,1.523104e+06,-18.0,11.066667,-17.833333,...,0,0,0,0,4.1715,2.0,16.992609,323.615540,100.0,NaN
5,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 05:00:00,948.925318,948.117326,1.524053e+06,-18.0,11.275000,-17.800000,...,0,0,0,0,3.3715,0.3,11.525623,268.210114,81.0,NaN
6,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 06:00:00,943.195856,942.197902,1.524995e+06,-18.0,11.266667,-17.800000,...,0,0,0,0,3.0715,0.0,12.620554,266.729584,10.0,NaN
7,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 07:00:00,461.699028,461.312800,1.525456e+06,-18.0,10.200000,-13.000000,...,0,0,0,0,2.5215,0.0,11.542478,266.423737,0.0,NaN
8,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 08:00:00,919.601632,919.536424,1.526376e+06,-18.0,11.533333,-17.566667,...,0,0,0,0,2.2215,0.0,12.522619,251.564957,69.0,NaN
9,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 09:00:00,916.454445,915.682541,1.527291e+06,-18.0,11.200000,-17.600000,...,0,0,0,0,2.1715,0.0,11.841756,250.463257,51.0,NaN
10,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 10:00:00,907.793881,907.974506,1.528199e+06,-18.0,11.100000,-17.900000,...,0,0,0,0,1.8215,0.0,10.495713,247.833603,52.0,NaN
11,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 11:00:00,887.743038,887.333508,1.529087e+06,-18.0,11.266667,-18.000000,...,0,0,0,0,2.0715,0.0,10.483357,254.054535,61.0,NaN
12,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 12:00:00,913.504323,913.308033,1.530000e+06,-18.0,11.350000,-18.000000,...,0,0,0,0,2.6215,0.1,10.703569,250.346085,55.0,NaN
13,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 13:00:00,928.013366,928.186031,1.530928e+06,-18.0,11.000000,-18.000000,...,0,0,0,0,3.4215,0.0,10.587917,252.181015,12.0,NaN
14,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 14:00:00,970.747584,970.725140,1.531899e+06,-18.0,11.400000,-18.075000,...,0,0,0,0,3.9715,0.0,12.646200,265.100983,100.0,NaN
15,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 15:00:00,908.022028,908.056494,1.532807e+06,-18.0,11.200000,-18.100000,...,0,0,0,0,4.3215,0.0,12.074766,259.695221,72.0,NaN
16,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 16:00:00,921.501136,921.306738,1.533728e+06,-18.0,11.425000,-18.100000,...,0,0,0,0,4.3215,0.0,11.542478,266.423737,86.0,NaN
17,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 17:00:00,934.422131,933.950085,1.534662e+06,-18.0,11.566667,-18.100000,...,0,0,0,0,3.7215,0.3,12.224107,256.372986,80.0,NaN
18,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 18:00:00,949.014749,948.620771,1.535611e+06,-18.0,10.650000,-18.100000,...,0,0,0,0,3.3715,0.1,11.525623,268.210114,95.0,NaN
19,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 19:00:00,941.528349,941.694472,1.536552e+06,-18.0,10.425000,-18.175000,...,0,0,0,1,3.0215,0.1,11.304229,260.837738,100.0,NaN
20,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 20:00:00,916.994942,915.835980,1.537468e+06,-18.0,9.900000,-18.166667,...,0,0,0,0,2.0715,0.1,10.587917,252.181015,99.0,NaN
21,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 21:00:00,928.151947,931.418264,1.538400e+06,-18.0,9.850000,-18.100000,...,0,0,0,0,2.1215,0.1,11.177405,255.068527,100.0,NaN
22,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 22:00:00,902.347303,902.330499,1.539302e+06,-18.0,9.775000,-18.100000,...,0,0,0,0,1.8715,0.6,11.275530,253.300674,100.0,NaN
23,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-01 23:00:00,875.333560,875.318754,1.540177e+06,-18.0,9.766667,-18.100000,...,0,0,0,0,1.8715,1.3,11.570515,264.644257,97.0,NaN
24,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 00:00:00,878.198807,878.359382,1.541056e+06,-18.0,10.150000,-18.100000,...,0,0,0,1,1.6215,0.2,12.646200,265.100983,98.0,NaN
25,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 01:00:00,900.104831,900.259960,1.541956e+06,-18.0,9.300000,-18.100000,...,0,0,0,0,1.3715,0.0,11.885453,268.264343,95.0,NaN
26,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 02:00:00,927.552590,927.347699,1.542883e+06,-18.0,8.233333,-18.200000,...,0,0,0,0,1.1215,0.0,10.931203,252.758453,100.0,NaN
27,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 03:00:00,916.380133,916.841510,1.543800e+06,-18.0,8.175000,-18.200000,...,0,0,0,0,1.0715,0.2,11.269782,243.435013,100.0,NaN
28,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 04:00:00,898.343263,898.251075,1.544698e+06,-18.0,7.933333,-18.200000,...,0,0,0,0,1.1215,0.3,12.245293,245.695465,100.0,NaN
29,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 05:00:00,924.202125,924.267386,1.545623e+06,-18.0,8.275000,-18.200000,...,0,0,0,0,0.9715,0.1,13.441071,249.623474,98.0,NaN
30,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 06:00:00,929.404211,928.433889,1.546551e+06,-18.0,8.200000,-18.150000,...,0,0,0,0,1.0215,0.3,14.689589,252.897186,100.0,NaN
31,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 07:00:00,908.541644,908.730410,1.547460e+06,-18.0,7.500000,-18.000000,...,0,0,0,0,1.0715,0.2,16.171976,253.178513,94.0,NaN
32,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 08:00:00,899.906028,900.084369,1.548360e+06,-18.0,8.075000,-18.000000,...,0,0,0,0,1.0215,0.0,18.532133,245.924500,100.0,NaN
33,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 09:00:00,919.204075,921.360961,1.549281e+06,-18.0,8.600000,-18.025000,...,0,0,0,0,0.9215,0.1,19.969458,242.049118,100.0,NaN
34,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 10:00:00,923.332455,922.431046,1.550204e+06,-18.0,8.700000,-18.000000,...,0,0,0,0,0.8715,0.7,21.273533,246.037506,100.0,NaN
35,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 11:00:00,908.494774,912.873206,1.551117e+06,-18.0,9.350000,-18.000000,...,0,0,0,0,1.1715,0.1,24.408424,232.791992,100.0,NaN
36,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 12:00:00,899.997511,899.390442,1.552016e+06,-18.0,8.966667,-17.966667,...,0,0,0,0,0.7715,1.9,23.838961,255.124268,100.0,NaN
37,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 13:00:00,908.089347,908.048742,1.552924e+06,-18.0,9.025000,-17.900000,...,0,0,0,0,0.7215,3.3,14.205182,278.746063,100.0,NaN
38,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 14:00:00,909.873606,911.790968,1.553836e+06,-18.0,9.050000,-17.900000,...,0,0,0,0,1.3215,0.1,16.099689,280.304779,94.0,NaN
39,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 15:00:00,881.266477,881.275321,1.554717e+06,-18.0,8.500000,-17.900000,...,0,0,0,0,1.4215,0.0,13.684735,296.564972,100.0,NaN
40,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 16:00:00,921.650531,920.446736,1.555638e+06,-18.0,8.350000,-17.925000,...,0,0,0,0,1.3715,0.0,14.186923,305.706787,48.0,NaN
41,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 17:00:00,949.849143,950.039557,1.556588e+06,-18.0,7.466667,-18.000000,...,0,0,0,0,0.9215,0.0,12.181625,288.970490,38.0,NaN
42,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 18:00:00,936.463493,936.589914,1.557524e+06,-18.0,7.425000,-18.075000,...,0,0,0,0,0.6215,0.0,10.308831,282.094727,45.0,NaN
43,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 19:00:00,927.383561,926.779445,1.558451e+06,-18.0,7.575000,-18.100000,...,0,0,0,0,0.5215,0.0,9.746631,265.763672,11.0,NaN
44,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 20:00:00,903.230570,903.625456,1.559355e+06,-18.0,7.325000,-18.100000,...,0,0,0,0,0.0215,0.0,11.440978,257.275635,39.0,NaN
45,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 21:00:00,947.727928,946.796583,1.560301e+06,-18.0,7.366667,-18.100000,...,0,0,0,0,-0.1785,0.0,11.177405,255.068527,94.0,NaN
46,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 22:00:00,901.975615,901.469564,1.561203e+06,-18.0,7.575000,-18.125000,...,0,0,0,0,-0.0285,0.3,10.594036,260.217651,61.0,NaN
47,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-02 23:00:00,891.134808,889.606209,1.562092e+06,-18.0,7.566667,-18.133333,...,0,0,0,0,-0.1785,0.1,11.792404,257.660919,76.0,NaN
48,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-03 00:00:00,875.846789,875.410732,1.562968e+06,-18.0,7.200000,-18.000000,...,0,0,0,0,-0.1785,0.0,10.661107,258.310669,94.0,NaN
49,e81b2358-de43-a16e-099e-4561b75d88ee,1b16f35f-77fc-3548-4bba-94630695e99e,22397407-6f6f-8118-a57e-7d29109182f2,2025-01-03 01:00:00,885.338550,885.542368,1.563853e+06,-18.0,6.850000,-18.000000,...,0,0,0,0,0.0715,0.0,10.308831,257.905243,83.0,NaN